export const Gents={
    title: "Gents Fashion",
    image1:"assests/Men/Mens/1.jpg",
    image2:"assests/Men/Mens/2.jpg",
    image3:"assests/Men/Mens/3.jpg",
    image4:"assests/Men/Mens/4.jpg",
    image5:"assests/Men/Mens/5.jpg",
    image6:"assests/Men/Mens/6.jpg",
    price1:"559 INR",
    price2:"459 INR",
    price3:"659 INR",
    price4:"759 INR",
    price5:"859 INR",
    price6:"959 INR",
}
export const Ladies={
    title: "Ladies Fashion",
    image1:"assests/Women/Womens/1.jpg",
    image2:"assests/Women/Womens/2.jpg",
    image3:"assests/Women/Womens/3.jpg",
    image4:"assests/Women/Womens/4.jpg",
    image5:"assests/Women/Womens/5.jpg",
    image6:"assests/Women/Womens/6.jpg",
    price1:"1559 INR",
    price2:"1459 INR",
    price3:"1659 INR",
    price4:"1759 INR",
    price5:"1859 INR",
    price6:"1959 INR",
}